### PR TITLE
Design improvements (closes #260)

### LINKED ISSUE #260: Design improvements
I plan to talk with the designer about making some improvements. Bellow are mine but feel free to add your own and I will pass them:

1. [x] Too hard to find a link to our Github on the website. Need to find a good place for it. *Added to the top menu. Lets add Twitter there as well and remove both from footer*.

2. [x] We have a really cool infographic but its hidden behind a very small "how it works" button. Need to make it more prominent and visible. *See design below*.

3. [x] ~Maybe make the "network" page a separate page~. Show a bigger map and move all text below. *See the design below*.

4. [x] Remove about, tos and privacy from the features page. *Move all to footer*.

5. [x] Include infographic in a better way in the Features pages. *See the design below*.

6. Design purge cache tool page. Probably an input field asking for a list of URLs to purge, with "Purge Now" button and a captcha + ratelimit per IP on our side. After purge show pretty output of our results json: *Will be done in a separate issue*.

```
{
"fastly": [
{
"status": "ok",
"id": "20727-1558573413-986072"
},
{
"status": "ok",
"id": "20726-1558577588-1041027"
},
{
"status": "ok",
"id": "20726-1558577588-1041028"
},
{
"status": "ok",
"id": "20726-1558577588-1041029"
},
{
"status": "ok",
"id": "20734-1558573890-1049626"
},
{
"status": "ok",
"id": "20735-1558578641-958658"
}
],
"maxcdn": {
"code": 200
},
"cloudflare": true,
"quantil": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<response><message>success</message></response>"
}
```

### PR DESCRIPTION
**Pull request by Drgy**

### CODE REVIEW

**Comment by jimaek** [comment]
1. https://dl.dropboxusercontent.com/s/epxdam9w3dzu6kc/dllhost_rcKvk81PNi.png
2. Maybe we can use an icon for newsletter as well? https://dl.dropboxusercontent.com/s/mdtjzqhijxhodi9/chrome_3qUMeJYND2.png it would fit better
3. Remove some buttons https://dl.dropboxusercontent.com/s/q6rc8vlf375nk2n/chrome_viv8g3oqh2.png
4. Also I don't think the pins match the design

**Comment by MartinKolarik** [comment]
> 4. Also I don't think the pins match the design

They are as they were before, I think that was the closest we could get to the design with css. I don't remember if we could use PNGs instead. @Drgy please check and if yes, ask @jimaek for the exports as well as the source image file in case we need to create a different color later.

**Comment by MartinKolarik** [comment]
5. The map is missing country borders.

**Comment by Drgy** [comment]
@jimaek can you please send exports and source image file of map markers

**Comment by jimaek** [comment]
https://snazzymaps.com/style/151/ultra-light-with-labels
[markers.zip](https://github.com/jsdelivr/www.jsdelivr.com/files/3407400/markers.zip)

**Comment by jimaek** [comment]
Lets also update stackpath logo everywhere to the new one https://www.stackpath.com/company/logo-and-branding/

**Comment by jimaek** [comment]
@Drgy Let me know when you are 100% finished to review it

**Comment by Drgy** [comment]
It should be all done, except the pins I can't find any changes but it seems like the correct ones are used.

**Comment by jimaek** [comment]
The live pins are very solid, while the design has soft colors and radius
https://dl.dropboxusercontent.com/s/wn974fggst88a7g/chrome_146nqrMnxp.png

**Comment by Drgy** [comment]
@jimaek it should be all now

**Pull request merged**
