### PR TITLE
Globalping Network page

### LINKED ISSUE #672: GP: network map
New page, design in Figma.

Related: https://github.com/jsdelivr/www.jsdelivr.com/issues/635, https://github.com/jsdelivr/globalping/issues/306

### PR DESCRIPTION
**Pull request by xbpcb**
Fix #672

### CODE REVIEW

**Comment by MartinKolarik** [comment]
- [ ] no horizontal scrolling please, just make it as long as needed

**Comment by jimaek** [comment]
We also wanted to make the map points much smaller and probably the map bigger and centered on large 4k screens

**Comment by MartinKolarik** [comment]
> We also wanted to make the map points much smaller and probably the map bigger and centered on large 4k screens

I'll be doing that part.

**Comment by MartinKolarik** [comment]
It appears we're either showing more details or the map or missing some styles when zoomed in closely (e.g. shops shouldn't be visible and also not interactive): https://dl.dropboxusercontent.com/scl/fi/c1o1x20ppr3r8gxp8r2sj/2024-11-11_15-42-49.png?rlkey=7hbmx92crx2c1cg2qmd0m8ncm&dl=0

**Comment by jimaek** [comment]
Thats a setting on my side, I disabled that stuff

**Comment by MartinKolarik** [comment]
You mean it applies some options based on the API key or where else are we loading config from?

**Comment by jimaek** [comment]
Map styles are now controlled in Google Cloud https://share.perfstack.net/2024/11/chrome_2024-11-12_12-15-02.png
But its basic stuff like visibility and colors

**Comment by MartinKolarik** [comment]
It's still showing a few things: https://dl.dropboxusercontent.com/scl/fi/h4l8gigf8fnernzkimj82/2024-11-12_12-24-38.png?rlkey=t8qq7096x10s9oou2b8utvvs2&dl=0 Also I think we can disable the "busy area" yellow background.

**Comment by jimaek** [comment]
Its not super clear but I think I disabled those things too, just wait a bit for cache to expire

**Comment by MartinKolarik** [comment]
I'm still seeing some: 
image

**Comment by MartinKolarik** [comment]
Also since you control the styles I think these red lines are up to you as well to hide?

image

**Comment by jimaek** [comment]
>Also since you control the styles I think these red lines are up to you as well to hide?

This one I was not able to find. No idea what its called

**Comment by xbpcb** [comment]
> > Also since you control the styles I think these red lines are up to you as well to hide?
> 
> This one I was not able to find. No idea what its called
In our custom rules we had a rule responsible for hiding these red lines:

{
    "featureType": "administrative",
    "elementType": "geometry.fill",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },

**Comment by jimaek** [comment]
I dont think thats something I can do on my side https://developers.google.com/maps/documentation/javascript/cloud-customization/taxonomy

**Comment by MartinKolarik** [comment]
Maybe disable the cloud styling and go back to the json styles? Seems it just makes everything harder.

**Comment by jimaek** [comment]
I was under the impression the cloud styling was a requirement for the migration away from the deprecated maps version

**Comment by xbpcb** [comment]
> Maybe disable the cloud styling and go back to the json styles? Seems it just makes everything harder.

They are forcing devs to use cloud-based styling:
1. As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead
2. The map is initialized without a valid Map ID, which will prevent use of Advanced Markers.
3. Styles property: styles to apply to each of the default map types. ..... This feature is not available when using a map ID, or when using vector maps (use cloud-based maps styling instead).

**Review by MartinKolarik — APPROVED** [review]

**Pull request merged**
