### PR TITLE
Remove PerfOps as a sponsor

### PR DESCRIPTION
**Pull request by BirkhoffLee**
#311 
Please check the file diff

### CODE REVIEW

**Comment by jimaek** [comment]
Need to also remove this part as well https://dl.dropboxusercontent.com/s/j5x374cmclm6ije/chrome_qYu67PKanq.png

**Comment by BirkhoffLee** [comment]
Done @jimaek

**Comment by jimaek** [comment]
LGTM

**Comment by BirkhoffLee** [comment]
Looks like the entire RUM section has to be removed.

**Comment by jimaek** [comment]
Maybe don't remove but hide it? We later should have an API of some kind to show the same data. So we could re-use the same design

**Comment by MartinKolarik** [comment]
@BirkhoffLee probably comment out this section in `landing-bottom` then and add a comment referencing this issue:

```
<section class="rum">
	<div class="container">
		<c-rum></c-rum>
	</div>
</section>
```

I think this is the only place where it's used.

**Pull request merged**
