### PR TITLE
GP: Add integrations page

### LINKED ISSUE #588: GP: Integrations page
Design in Figma

Content to add, in this order:
- REST API
- CLI/Scripting
- Slack
- GitHub Bot
- ChatGPT (coming soon)
- Zappier (coming soon)
- IFTTT (coming soon)
- GitHub Actions (coming soon)

I'll add the descriptions and links myself to the PR.

### PR DESCRIPTION
**Pull request by xbpcb**
Fix #588

### CODE REVIEW

**Comment by jimaek** [comment]
LGTM @MartinKolarik please check

**Comment by MartinKolarik** [comment]
- [ ] the hover effect moves the box itself/other boxes
 
@jimaek the page also seems to be missing some kind of a headline

**Comment by jimaek** [comment]
I thought it was self explanatory so I didn't think to add anything else. You sure it's needed?

**Comment by MartinKolarik** [comment]
Self-explanatory maybe, but it looks weird without it; I would expect something similar to what the home page / slack / cli have at the top

**Comment by jimaek** [comment]
This is why we have Figma comments :)

But that header is huge, I don't think it fits this directory style page. The goal is different, it's just a list

**Comment by MartinKolarik** [comment]
Yes I didn't realize it was a complete page already and only responded to the part where I was tagged. 

Regardless, the page needs a message to send. E.g. (feel free to rephrase) "A full-featured API for your own app, easy to use CLI for automation, or a no-code chat bot - our integrations cover it all"

**Comment by jimaek** [comment]
That message is different per integration which I already added. Not sure what cool thing we could add as header without being repetitive. It's a list of supported integrations, plus the best ones have their own dedicated pages as well

**Pull request merged**
