### PR TITLE
fix: add router ignore to discord link

### PR DESCRIPTION
**Pull request by ayuhito**
Fixes the redirect since it seemed to be the client side router responsible for the bug.

### CODE REVIEW

**Comment by MartinKolarik** [comment]
There are multiple ways to bypass the client-side router, but I have already changed it to point directly to discord. I see no reason to use the redirect here - it makes sense when you want to post the text version of the link, but here it doesn't really matter what's the URL when you just click an icon.

**Comment by ayuhito** [comment]
We do want to share the link on Twitter and other places, so we do need to get the redirect working.

I was thinking to change the icon link to the redirect as there is a possible interaction of a user copying the link from the icon to share. I can alter that if you don't think that's appropriate though.

**Comment by MartinKolarik** [comment]
But the redirect works, just not when you click the link on our website. Anyway, you can add `router-ignore` class to the link and then you don't have to set up a client-side route for it (and can keep the link to `/discord`).

**Comment by ayuhito** [comment]
Yup, that works. I think there's a slight issue with caching though with this solution, which might affect live users. It works fine if I use an incognito tab, but the catch all still occurs with my normal tabs, even with Devtools Network cache disabled. Is that ok to push?

**Comment by MartinKolarik** [comment]
Hmm ok, it indeed doesn't currently work in the live version but it's because of an unrelated caching issue. You can ignore that here, just add the class and change href.

**Comment by MartinKolarik** [comment]
I think it must be on the link and not the image?

**Pull request merged**
