### PR TITLE
feat: add discord links

### PR DESCRIPTION
**Pull request by ayuhito**
Adds a redirect for `/discord` and the Discord link where socials are shown.

### CODE REVIEW

**Comment by ayuhito** [comment]
I do have a slight concern about it adding a little too much clutter, but that might just be me. Will make a subsequent PR for the redesign branch if this is approved.

**Comment by MartinKolarik** [comment]
@jimaek wdyt? 
image

**Comment by ayuhito** [comment]
Personally, I think if the esm.run part wasn't there, it would look more natural. Fortunately that's already done in the redesign branch, so it shouldn't be problematic to include it there imo.

**Comment by jimaek** [comment]
Looks good to me, at least on the current site. On the new one we will need to find a better location

**Pull request merged**
