### PR TITLE
Fix about history page

### PR DESCRIPTION
**Pull request by xbpcb**
Fix mobile and desktop styles of the About and History pages

### CODE REVIEW

**Comment by xbpcb** [comment]
Not ready yet.

**Comment by xbpcb** [comment]
There is a problem with the tests, the test for the search form on the main page is currently broken due to the fact that the jsDelivr package is expected first, but currently 2 new packages have appeared and therefore the test does not pass. Will fix it later in the  separate PR

**Comment by MartinKolarik** [comment]
The test issue is indeed result of some search logic changes. It's a bit unfortunate but we can just change the test.

**Comment by MartinKolarik** [comment]
Adding back `-webkit-background-clip: text` because the prefix is needed in Chrome and autoprefixes doesn't add it.

**Comment by MartinKolarik** [comment]
- [ ] 
image

**Pull request merged**
