### PR TITLE
Added search block into package page

### PR DESCRIPTION
**Pull request by HesyRa**
https://github.com/jsdelivr/www.jsdelivr.com/issues/124

### CODE REVIEW

**Comment by MartinKolarik** [comment]
1. The search results can't just appear in the package page. The page needs to be changed back to home as soon as user starts typing (so that there's no package page content below search results, and the URL is correct)
2. It should probably use a smaller search input in the package page because it currently takes too much space (maybe above "Get a badge for your package" ?).

Check the old version of the website to see how this should work: https://jsdelivr-com-old.herokuapp.com/

**Comment by HesyRa** [comment]
@MartinKolarik Updated. Please check.

**Comment by MartinKolarik** [comment]
@HesyRa thanks, that's better. I made a few improvements (check commits for details) and I think it's good to go now.

@jimaek any feedback?

**Comment by HesyRa** [comment]
@MartinKolarik Thank. No questions here, everything is clear.

**Comment by jimaek** [comment]
Looks good to me. Merge if the code is good to go.

Thank you both

**Pull request merged**
