### PR TITLE
Small updates

### PR DESCRIPTION
**Pull request by jimaek**
- Added links to new site
- Removed email
- Removed links to cdn/dnsperf

### CODE REVIEW

**Comment by MartinKolarik** [comment]
We should keep the email.

**Comment by jimaek** [comment]
Its listed in the about page and privacy policy pages and our github.

**Comment by MartinKolarik** [comment]
How about something like this instead?

image

Then we can keep the name and I think it's also a better position since it's related to the "Designed, developed, and maintained by" part above.

**Comment by jimaek** [comment]
Ok, lets do that. Maybe then replace "by" with "and"

**Pull request merged**
