### PR TITLE
GP: sponsors page

### LINKED ISSUE #671: GP: Sponsors
New page, design in Figma.

@jimaek please add a list here for each section.

### PR DESCRIPTION
**Pull request by xbpcb**
Fix #671 
Should be merged after the https://github.com/jsdelivr/www.jsdelivr.com/pull/683

### CODE REVIEW

**Comment by jimaek** [comment]
Remove all sponsors and add everyone from the current homepage list to Bronze.

Except from:
Gold:
- Zenlayer

Also needs a title "Globalping Sponsors - Join the team to expand the network"

**Comment by MartinKolarik** [comment]
- [ ] Missing the top background
 - [ ] Wrong icons in the list at the top
 - [ ] The green boxes need the same padding as sponsors https://dl.dropboxusercontent.com/scl/fi/wdqdnv07rg9zb9y6144hu/2024-09-30_12-53-43.png?rlkey=zhd45sw5m78g4b5ceefuyd2ov&dl=0

**Comment by MartinKolarik** [comment]
@jimaek the list of sponsors is now ok?

**Comment by jimaek** [comment]
Yes looks correct

**Pull request merged**
