### PR TITLE
Optimize SVG files

### PR DESCRIPTION
**Pull request by XhmikosR**
I used the latest svgo, and also made a few manual changes like lowercasing hex colors for better gzip compression. The files should still be editable, and I tried to follow pretty print where used like checkbox.svg and logo-horizontal.svg; the difference is negligible after compression anyway.

I can post my svgo config if needed.

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Thanks for bringing this up. I rerun svgo with config we already use on other projects (with similar results).

**Comment by XhmikosR** [comment]
Your config is different than the one I used. You removed the viewbox, I personally keep it. I suggest that you revert your patch.

**Comment by XhmikosR** [comment]
Plus you reverted my manual changes like the lowercase hex colors...

**Comment by MartinKolarik** [comment]
> Your config is different than the one I used

Sure, that was the point.

Color case doesn't matter if it's consistent in individual files, which I think it is. If svgo was able to rewrite that automatically, I'd add it to the config but it's not worth maintaining manually.

**Comment by XhmikosR** [comment]
Color case does matter in compression. That was the whole idea behind this PR: achieve the best possible compression while keeping readability.

**Comment by XhmikosR** [comment]
You do not have to maintain anything. svgo wouldn't change the case if it's consistent, which is what my patch used. You basically reverted all my changes in a PR of mine.

**Comment by MartinKolarik** [comment]
> Color case does matter in compression.

Can you explain how? I'm really curious about that.

**Pull request merged**
