### PR TITLE
Optimize the package page for longer package names

### PR DESCRIPTION
**Pull request by MartinKolarik**

### CODE REVIEW

**Comment by MartinKolarik** [comment]
@jimaek merge if ok.

**Comment by MartinKolarik** [comment]
@jimaek did we hit some limit on number of deployments? 😆

**Comment by jimaek** [comment]
https://dl.dropboxusercontent.com/s/eaaqh38raivc4r7/chrome_2017-09-02_11-21-51.png

**Comment by MartinKolarik** [comment]
Strange that CI didn't fail. Can you try manual deploy now? If it doesn't work I'll check it in the evening.

**Comment by jimaek** [comment]
Cant trigger manually. It works only automatically. You can commit something to trigger it

**Comment by jimaek** [comment]
same error

**Pull request merged**
