### PR TITLE
Update total stats chart

### LINKED ISSUE #110: Stats total
chrome_2017-08-31_16-24-45

1. How about "lodash CDN stats for last 30 days" instead?
2. Remove a bit of white space?
3. The line is too empty I think. Maybe we can show dates by default without hover?

### PR DESCRIPTION
**Pull request by MartinKolarik**
Closes #110

### CODE REVIEW

**Comment by jimaek** [comment]
Actually, how about this.
"lodash had 30.000.000 CDN hits in the last 30 days" (tweet button)

I dont think we have anywhere the combined number.

**Comment by MartinKolarik** [comment]
Badge shows the total but 👍 for tweet

**Comment by jimaek** [comment]
it would be even cooler if we could generate a small image on the fly with the stats that would attach to the tweet :p but thats too much

**Comment by MartinKolarik** [comment]
@jimaek check now

**Comment by jimaek** [comment]
That wont work for less popular projects. If someone gets 20k hits he could tweet it because its a lot to him. But if it says its #2458 project then he wont.

Lets also work on the chart near the footer in this PR.

**Comment by MartinKolarik** [comment]
Well they can always modify the tweet before posting it. Showing the rank is more important and interesting for people than the number of hits IMHO.

I already updated the chart and I'd like to keep it as it is now. Styling charts is always a big pain and I think it looks exactly as it should right now.

**Comment by jimaek** [comment]
>Well they can always modify the tweet before posting it. Showing the rank is more important and interesting for people than the number of hits IMHO.

Only for those with a high rank. Someone with rank 2000 wont feel the same way. But 20000 hits sounds big enough to be proud of and tweet about it.

The chart still looks like part of the background. Only the numbers on the right hint that its a chart. And easy to miss them.

I want to add more features to make it look like a real chart so people wont ignore/skip it

**Comment by MartinKolarik** [comment]
As I said, they can always modify the tweet. I'm quite sure in most cases this will be used with popular projects where the rank is interesting. Also, we need to show it somewhere on the website.

>The chart still looks like part of the background. Only the numbers on the right hint that its a chart. And easy to miss them.

That's good! That was the original intention of this design, it isn't supposed to look like a regular chart.

**Comment by jimaek** [comment]
>Also, we need to show it somewhere on the website.

Change it to this to see how it looks like:
lodash is the 8th most popular package on jsDelivr,

>That's good! That was the original intention of this design, it isn't supposed to look like a regular chart.

But not too much, otherwise nobody will even see it. I think we should show the dates by default https://dl.dropboxusercontent.com/s/uxtsulqzvw6xoqm/chrome_2017-08-31_19-07-14.png maybe with a doted line. And then on hover you see the hits. 
Or even just show everything by default and on hover just highlight where you are.

**Comment by MartinKolarik** [comment]
>Change it to this to see how it looks like:
lodash is the 8th most popular package on jsDelivr,

Keep or revert?

**Comment by jimaek** [comment]
Either keep or completely remove the rating :)

**Comment by MartinKolarik** [comment]
So keep you say 😆

**Comment by MartinKolarik** [comment]
Let's merge this and I'll play with the chart in a next PR.

**Comment by MartinKolarik** [comment]
Actually, here's an idea: Show only if rank < 100 ?

**Comment by jimaek** [comment]
Yeah that would be great

**Pull request merged**
